apiVersion: v1
kind: Service
metadata:
  name: ingress-nginx-metric-service
  namespace: ingress-nginx
  labels:
    app.kubernetes.io/name: ingress-nginx
    app.kubernetes.io/part-of: ingress-nginx
    release: mon
spec:
  selector: 
    app.kubernetes.io/name: ingress-nginx
    app.kubernetes.io/part-of: ingress-nginx
  ports:
  - name: metrics-svc-port
    protocol: TCP
    port: 10254
    targetPort: 10254

---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: ingress-nginx-metric-service-sm
  namespace: monitoring
  labels:
    app.kubernetes.io/name: ingress-nginx
    app.kubernetes.io/part-of: ingress-nginx
    release: mon
spec:
  jobLabel: ingress-metrics
  selector:
    matchLabels:
      app.kubernetes.io/name: ingress-nginx
      app.kubernetes.io/part-of: ingress-nginx
      release: mon
  namespaceSelector:
    matchNames:
    - ingress-nginx
  endpoints:
  - port: metrics-svc-port
    interval: 60s
    path: /metrics

