apiVersion: extensions/v1beta1  
kind: Ingress  
metadata:  
  name: grafana
  namespace: monitoring
  annotations:
spec:  
  rules:
  - host: grafana-k8s-1.bdswiss.com
    http:
      paths:
      - backend:
          serviceName: mon-grafana
          servicePort: 80
        path: /

