apiVersion: autoscaling/v2beta1
kind: HorizontalPodAutoscaler
metadata:
  name: mt4-trading-api-web-real01
  namespace: mt4-trading-api-real01
spec:
  maxReplicas: 4
  minReplicas: 2
  scaleTargetRef:
    apiVersion: extensions/v1beta1
    kind: Deployment
    name: mt4-trading-api-web-real01
  metrics:
  - type: Resource
    resource:
      name: memory
      targetAverageUtilization: 150
